kokkos/kokkos-core-wiki

workflows/deploy_wiki.yml

Setup automatic deployment

---

API-Reference/API-Core.md
API-Reference/API-View.md
API-Reference/Detection-Idiom.md
API-Reference/Kokkos::DynamicView.md
API-Reference/Kokkos::MDRangePolicy.md
API-Reference/Kokkos::View.md
API-Reference/Kokkos::create_mirror.md
API-Reference/Kokkos::fence.md
API-Reference/Kokkos::parallel_reduce.md
API-Reference/Kokkos::partition_space.md
API-Reference/Kokkos::realloc.md
API-Reference/Kokkos::resize.md
API-Reference/Kokkos::view_alloc.md
API-Reference/Mathematical-Constants.md
API-Reference/Mathematical-Functions.md
API-Reference/Numeric-Traits.md
API-Reference/Numerics.md
ExecutionPolicyConcept.md
Iterators.md
MemorySpaceConcept.md
StdModSeq.md
StdNonModSeq.md
StdPartioningOps.md
_Sidebar.md

Merge changes from private wiki

---

API-Reference/Data-Parallelism.md

Reworked explanation of `parallel_*` tags for clarity

Data-Parallelism.md: rework explanation of tags

---

ProgrammingGuide/Kokkos-and-Virtual-Functions.md

Cleaned up git commit history.

Kokkos-and-Virtual-Functions.md: add Kokkos::fence() to UVM example

---

ProgrammingGuide/Compiling.md
ProgrammingGuide/Interoperability.md

Remove stray pthread mentions

---

source/API/core/builtinreducers/MaxLoc.md
source/API/core/builtinreducers/MinLoc.md
source/API/core/builtinreducers/MinMax.md
source/API/core/builtinreducers/MinMaxLoc.md

- fixed links in MaxLoc.md
- fixed links in MinLoc.md
- fixed links in MinMax.md
- fixed links in MinMaxLoc.md

#32: Fix built in reducers

---

source/testing-and-issue-tracking/Requirements-Issues-and-Feedback.md
source/testing-and-issue-tracking/Testing-Process-Details.md
source/testing-and-issue-tracking/Testing-Processes.md
source/testing-and-issue-tracking/Testing-Workflow-Components.md

- fixed grammar in testing-and-issue-tracking/Requirements-Issue…s-and-Feedback.md
- removed blank lines and fixed formatting in testing-and-issue-tracking/Testing-Process-Details.md
- removed blank line from testing-and-issue-tracking/Testing-Processes.md
- fixed links and removed blank lines in testing-and-issue-tracking/Testing-Workflow-Components.md

#57: Fix testing-and-issue-tracking

---

source/API/algorithms/std-algorithms/StdMinMaxElement.md
source/API/core/CStyleMemManagement.md
source/API/core/Detection-Idiom.md
source/building.md
source/contributing.rst
source/requirements.rst

- removed blank lines, br tag and fixed grammar in building.md
- fixed link in contributing.rst
- removed blank lines and br tags in API/core/CStyleMemManagement.md
- removed blank lines and fixed links in API/core/Detection-Idiom.md
- fixed formatting and removed blank lines in requirements.rst
- removed blank lines and fixed links in API/algorithms/std-algorithms/StdMinMaxElement.md
Closes #57

#57: Fix remaining files

---

.gitignore

- added /docs/generated_docs to .gitignore
Closes #83

#83: Add generated docs dir to gitignore

---

docs/source/API/core-index.rst
docs/source/contributing.rst
docs/source/index.rst
docs/source/keywords.rst
docs/source/requirements.rst
docs/source/testing-and-issue-tracking.rst
docs/source/usecases.rst
docs/source/videolectures.rst

- hid toctree for core-index.rst and added a table
- removed blank line in contributing.rst
- removed blank lines in index.rst
- removed blank lines in keywords.rst
- removed blank line in requirements.rst
- removed blank line in testing-and-issue-tracking.rst
- removed blank line in usecases.rst
- removed blank lines in videolectures.rst

#95: Enchanced and cleaned rst files

---

docs/source/API/algorithms/std-algorithms-index.rst
docs/source/API/containers-index.rst
docs/source/API/core/Execution-Policies.rst
docs/source/API/core/STL-Compatibility.rst
docs/source/API/core/Spaces.rst
docs/source/API/core/policies/ThreadVectorRange.rst

- hid toctree for containers-index.rst and added a table
- hid toctree for Execution-Policies.rst and added missing links
- removed blank lines in Spaces.rst
- reduced toctree depth and removed blank line in std-algorithms-index.rst
- fixed formatting in STL-Compatibility.rst
- fixed formatting and removed blank line in ThreadVectorRange.rst

#95: Improve RST files

---

docs/source/edit_button_handler.py

- removed anything related to image from previous concept
- added check if the edit button is already added to the HTML file
closes #119

#119: Fix edit button duplication

---

docs/source/API/core/numerics/mathematical-functions.md

* Document that they were promoted to the `Kokkos::` namespace
* Document new functions that were added in 3.7

Update documentation of the common mathematical functions

---

docs/source/API/core/numerics/numeric-traits.md

Update numeric traits document removal of reciprocal_overflow_threshold

---

docs/source/API/core/numerics/mathematical-functions.md

Document addition of 3-argument version of hypot math function

---

docs/source/API/core/view/realloc.md

Corresponding to https://github.com/kokkos/kokkos/pull/5035.

Document new realloc overloads taking Kokkos::view_alloc() return type

---

docs/source/API/core/view/view.md

Corresponding to https://github.com/kokkos/kokkos/pull/5190, https://github.com/kokkos/kokkos/pull/5188, and https://github.com/kokkos/kokkos/pull/4618.

Update View constructor requirements

---

docs/source/API/core/view/view_like.md
docs/source/API/core/view/view_like.rst

- API/core/view/view_like transition from .md to .rst
Below render of the API/core/view/view_like after transition:

#120: API-core-view-view_like from md to rst

---

docs/source/API/core/numerics/mathematical-functions.md

Document addition of fused multiply-add math function

---

docs/source/API/core/view/create_mirror.md
docs/source/API/core/view/resize.md

Corresponding to https://github.com/kokkos/kokkos/pull/4844.

Document new resize overloads taking Kokkos::view_alloc() return type

---

docs/source/API/core/Macros.md
docs/source/keywords.rst

Document cmake option and macro for NVIDIA Hopper GPU arch

---

docs/source/usecases.rst
docs/source/usecases/WindowsHeader.md

for https://github.com/kokkos/kokkos/pull/5541

Short explanation to windows.h problem

---

docs/source/API/core/memory_spaces.md

Documentation for [#5405](https://github.com/kokkos/kokkos/pull/5405)

`SharedHostPinnedSpace` documentation

---

docs/source/API/core/policies/TeamThreadMDRange.md
docs/source/API/core/policies/TeamVectorMDRange.md
docs/source/API/core/policies/ThreadVectorMDRange.md

Fixed some typos, deleted incorrectly left examples from previous commits and slightly adjusted correct examples.

Fixed TeamMDRange policies documentations

---

docs/source/API/core/policies/RangePolicy.md

In reference to https://github.com/kokkos/kokkos/pull/4875#issuecomment-1250372202

Document RangePolicy chunk_size for SYCL

---

docs/source/API/algorithms/Sort.md

Fix a few places with unclear/imprecise wording

Minor edits to nested sort

---

docs/source/API/algorithms/Random-Number.md

Add an example of random number generation

---

docs/source/API/core/parallel-dispatch/parallel_reduce.rst

co-authored-by: @PhilMiller 
this fixes my mistake for PR #258

Fix wording for PR 258 merged by mistake by me

---

.github/workflows/deploy_docs.yml

Build docs on pull request

---

docs/source/API/core/Numerics.rst
docs/source/API/core/numerics/bit-manipulation.rst

Corresponds to kokkos/kokkos#4577

Add documentation for `<Kokkos_BitManipulation.hpp>` header

---

docs/source/API/core/KokkosConcepts.rst

* API/core/KokkosConcepts transition from .md to .rst
before (.md) | after (.rst)
:----------------: | :-------------:

#120: API-core-KokkosConcepts from md to rst

---

docs/source/requirements.rst

Update compiler requirements for 4.0

---

docs/source/API/core/view/view.rst

fix error in View constructor

---

docs/source/API/core/Macros.rst
docs/source/keywords.rst

Add NVIDIA Ada GPU architecture

---

docs/source/API/core/numerics/bit-manipulation.rst

Document addition of `byteswap`

---

docs/source/API/core/parallel-dispatch/ParallelForTag.rst
docs/source/API/core/parallel-dispatch/ParallelReduceTag.rst
docs/source/API/core/parallel-dispatch/ParallelScanTag.rst
docs/source/API/core/parallel-dispatch/fence.rst
docs/source/API/core/parallel-dispatch/parallel_for.rst
docs/source/API/core/parallel-dispatch/parallel_reduce.rst
docs/source/API/core/parallel-dispatch/parallel_scan.rst
docs/source/API/core/spaces/partition_space.rst
docs/source/API/core/view/view_alloc.rst

remove trailing parens from titles everywhere

---

docs/source/API/core/numerics/mathematical-functions.rst
docs/source/known-issues.rst

Prompted by discussion on Slack

Document known issues with using directives and math functions

---

docs/source/API/core/Utilities.rst
docs/source/API/core/utilities/device_id.rst
docs/source/API/core/utilities/num_threads.rst

Document `device_id()` and `num_threads()`

---

docs/source/keywords.rst

Remove mentions of libnuma

---

docs/source/API/core/execution_spaces.rst
docs/source/API/core/memory_spaces.rst

This pull request adds the SYCL execution space and SYCL memory spaces.

Update execution and memory spaces

---

docs/source/API/core/numerics/bit-manipulation.rst

Corresponds to kokkos/kokkos#6101

Update documentation of `<Kokkos_BitManipulation.hpp>` to reflect the addition of `bit_cast`

---

docs/source/ProgrammingGuide/Atomic-Operations.md
docs/source/ProgrammingGuide/HierarchicalParallelism.md
docs/source/usecases/MDRangePolicy.md

We found 3 warnings here:
https://github.com/kokkos/kokkos-core-wiki/issues/433#issuecomment-1622198505
There are fixed with this PR

#433 : Fix last warnings to build warnings-free

---

docs/source/API/core/Utilities.rst
docs/source/API/core/printf.rst

Corresponds to https://github.com/kokkos/kokkos/pull/6083.

Add documentation for Kokkos::printf

---

docs/source/API/containers/Unordered-Map.rst

@masterleinad, @fnrizzi: This never got merged into PR200 via https://github.com/marcinwrobel1986/kokkos-core-wiki/pull/1.

Add UnorderedMapInsertOps

---

docs/source/API/core/utilities/printf.rst

Add an usage example and a note

Improve `Kokkos::printf` doc

---

docs/source/API/core/Utilities.rst
docs/source/API/core/utilities/min_max_clamp.rst

Loosely related to kokkos/kokkos#6687

Document `Kokkos::{min,max,minmax,clamp}`

---

docs/source/API/core/utilities/min_max_clamp.rst

Corresponding to kokkos/kokkos#6687

Document the addition of `<Kokkos_Clamp.hpp>` and `<Kokkos_MinMax.hpp>` in 4.3

---

docs/source/license.rst

Copied from https://github.com/kokkos/kokkos/blob/2d273c86a5226a0e84061ed477db0ccc55ff8dec/LICENSE

Update license file

---

docs/source/keywords.rst

Update the documentation for AMD GPU in line with the Nvidia documentation. I have added the documentation about MI300 after getting the approval of AMD.

Update documentation for AMD GPU architecture

---

docs/source/API/core/view/create_mirror.rst

This PR aims to mention the changes of [PR #6917](https://github.com/kokkos/kokkos/pull/6917) in the Kokkos documentation.

Uniformize create_mirror* parameter name for views

---

docs/source/keywords.rst

Improve backend selection documentation

---

docs/source/API/alphabetical.rst
docs/source/API/containers-index.rst
docs/source/API/containers/vector.rst

Deprecated in kokkos/kokkos#6252

Mark vector as deprecated

---

docs/source/ProgrammingGuide/Compatibility.md

Update stand alone header file list

---

docs/source/API/core/view/view.rst
docs/source/conf.py

Screenshots below
Documentation for kokkos/kokkos#6830

add documentation for kokkos/kokkos#6830

---

docs/source/ProgrammingGuide/Initialization.rst

Add a newline between the blocks explaining the superscripts for readability.

Initialization.rst: small cosmetic change

---

.github/workflows/deploy_docs.yml

This allows introspecting of the generated documentation in pull requests.

GitHub CI: Create artifact of the generated documentation

---

docs/source/API/core/initialize_finalize/finalize.rst
docs/source/ProgrammingGuide/View.rst

core(view): broken link

---

docs/source/keywords.rst

Corresponds to https://github.com/kokkos/kokkos/pull/7550

Document ZEN4 cpu arch

---

docs/source/keywords.rst

Document RISC-V architectures

---

docs/source/API/core/policies/ThreadVectorRange.rst

policies(ThreadVectorRange): Fix index in example code

---

build_requirements.txt
docs/source/conf.py

Try to use extension published by sphinx-contrib

Set up Google Analytics

---

docs/source/get-started/configuration-guide.rst

https://github.com/kokkos/kokkos/pull/7877

Document support for AMD Zen5

---

docs/source/API/core/numerics/mathematical-constants.rst
docs/source/API/core/numerics/mathematical-functions.rst
docs/source/get-started/configuration-guide.rst

Document GCC Quad-Precision Math Library support

---

docs/source/get-started/configuration-guide.rst

https://github.com/kokkos/kokkos/blob/9663825a5da477c9cd450b915088efbb5ce74df1/cmake/kokkos_enable_options.cmake#L61-L67

Fix default value of Kokkos_ENABLE_DEBUG

---

docs/source/deprecations.rst

fixes https://github.com/kokkos/kokkos-core-wiki/issues/674
@ldh4 @masterleinad please take a look

Add deprecations of 4.6

---

docs/source/get-started/configuration-guide.rst

Support added in https://github.com/kokkos/kokkos/pull/8092

Document NVIDIA Ampere 8.7 arch (Jetson Orin)

---

docs/source/get-started/configuration-guide.rst

Add note about rdc and cuda having problems with shared libs

---

docs/source/get-started/requirements.rst

Minimum compiler requirements for Kokkos 5.x

Add minimum requirements for 5.x

---

docs/source/get-started/configuration-guide.rst

Linked to PR https://github.com/kokkos/kokkos/pull/8518

Add removal notes for Kepler GPU arch
