_Sidebar.md

The names on the side bar in the containers section do not match the name of the associated classes. Not sure why that was done this way. It just makes them harder to find.

Update side to match the name of the class

---

ProgrammingGuide/Compiling.md

@ibaned no more editing directly on the Kokkos wiki

Fix bulleting of ARCH_AMPERE options

---

ProgrammingGuide/Kokkos-and-Virtual-Functions.md
UseCases/VirtualFunctions.md

Fixed urls of images in `Kokkos-and-Virtual-Functions` and `VirtualFunctions` that were not displaying properly.

fix image urls in virtual function pages

---

source/API/core/builtin_reducers.rst
source/API/core/builtinreducers/BAnd.md
source/API/core/builtinreducers/BOr.md
source/API/core/builtinreducers/LAnd.md
source/API/core/builtinreducers/LOr.md
source/API/core/builtinreducers/Max.md
source/API/core/builtinreducers/MaxLoc.md
source/API/core/builtinreducers/Min.md
source/API/core/builtinreducers/MinLoc.md
source/API/core/builtinreducers/MinMax.md
source/API/core/builtinreducers/MinMaxLoc.md
source/API/core/builtinreducers/Prod.md
source/API/core/builtinreducers/Sum.md

- reorganized API/core/builtin_reducers
- fixed links, removed unnecessary indentation, removed char "" in order to render C++ block corectly in API/core/builtinreducers/BAnd`
- fixed links, removed unnecessary indentation, removed char "" in order to render C++ block corectly in API/core/builtinreducers/BOr`
- fixed links, removed unnecessary indentation, removed char "" in order to render C++ block corectly in API/core/builtinreducers/LAnd`
- fixed links, removed unnecessary indentation, removed char "" in order to render C++ block corectly in API/core/builtinreducers/LOr`
- fixed links, removed unnecessary indentation, removed char "" in order to render C++ block corectly in API/core/builtinreducers/Max`
- fixed links, removed unnecessary indentation, removed char "" in order to render …

#34: Reorganize and fix builtin reducers 

---

source/API/core/atomics.rst
source/API/core/atomics/atomic_compare_exchange.md
source/API/core/atomics/atomic_compare_exchange_strong.md
source/API/core/atomics/atomic_exchange.md
source/API/core/atomics/atomic_fetch_op.md
source/API/core/atomics/atomic_load.md
source/API/core/atomics/atomic_op.md
source/API/core/atomics/atomic_op_fetch.md
source/API/core/atomics/atomic_store.md

- changed order in API/core/atomics (to alphabetical order)
- removed unnecessary indentation and too many blank lines in 'API/core/atomics/atomic_compare_exchange'
- removed unnecessary indentation in 'API/core/atomics/atomic_compare_exchange_strong'
- removed unnecessary indentation in 'API/core/atomics/atomic_exchange'
- removed unnecessary indentation and too many blank lines in 'API/core/atomics/atomic_fetch_op'
- removed unnecessary indentation and too many blank lines in 'API/core/atomics/atomic_load'
- removed unnecessary indentation and too many blank lines in 'API/core/atomics/atomic_op'
- removed unnecessary indentation, dot and too many blank lines in 'API/core/atomics/atomic_op_fetch'
- removed unnecessary indentation and too many blank lines in …

#34: Fix API-core-atomics

---

source/API/core-index.rst
source/API/core/Task-Parallelism.md
source/API/core/fence.md
source/API/core/parallel_for.md
source/API/core/parallel_reduce.md

- changed order in API/core (first functions, then alphabetical order)
- fixed headings and grammar in API/core/Task-Parallelism (previously incorrect rendering)
- fixed links and removed namespace in API/core/fence
- removed blank line and removed unnecessary indentation in API/core/parallel_for
- removed blank line in API/core/parallel_reduce

#34: API core fixes

---

source/API/core/Execution-Policies.rst
source/API/core/policies/ExecutionPolicyConcept.md
source/API/core/policies/MDRangePolicy.md
source/API/core/policies/NestedPolicies.md
source/API/core/policies/RangePolicy.md
source/API/core/policies/TeamHandleConcept.md
source/API/core/policies/TeamPolicy.md
source/API/core/policies/TeamThreadRange.md
source/API/core/policies/TeamVectorRange.md
source/API/core/policies/ThreadVectorRange.md

- fixed warning, removed blank lines and added ExecutionPolicyConcept, MDRangePolicy, NestedPolicies in Execution-Policies.rst
- fixed links in ExecutionPolicyConcept and added missing to API/core/policies
- fixed indentation, formatted in NestedPolicies and added missing to API/core/policies
- removed doubled text, fixed headings and fixed indentation in TeamHandleConcept and added missing to API/core/policies
- fixed indentation, grammar and removed blank lines in MDRangePolicy.md
- removed blank lines and fixed indentation in RangePolicy.md
- fixed links, fixed indentation, removed blank lines and fixed grammar in TeamPolicy.md
- fixed indentation and fixed links in TeamThreadRange.md
- fixed grammar, indentation, removed blank lines and fixed links in TeamVectorRange.md
- fixed links …

#32: Fix policies

---

source/API/core/initialize_finalize/ScopeGuard.md
source/API/core/initialize_finalize/finalize.md
source/API/core/initialize_finalize/initialize.md
source/API/core/numerics/mathematical-constants.md
source/API/core/numerics/mathematical-functions.md
source/API/core/numerics/numeric-traits.md
source/API/std-algorithms/StdMinMaxElement.md
source/API/std-algorithms/StdModSeq.md
source/API/std-algorithms/StdNonModSeq.md
source/API/std-algorithms/StdNumeric.md
source/API/std-algorithms/StdPartioningOps.md
source/API/std-algorithms/StdSorting.md

- fixed links, changed cpp to c++ code block, removed blank lines in finalize.md
- fixed links and changed cpp to c++ code block in initialize.md
- fixed links in mathematical-constants.md
- fixed links in mathematical-functions.md
- fixed links in numeric-traits.md
- fixed links and changed cpp to c++ code block in ScopeGuard.md
- added missing ScopeGuard to API/core/initialize_finalize
- changed cpp to c++ code block in StdMinMaxElement.md
- changed cpp to c++ code block in StdModSeq.md
- changed cpp to c++ code block in StdNonModSeq.md
- fixed links, removed blank lines, fixed indentation in StdNumeric.md
- changed cpp to c++ code block in StdPartioningOps.md
- changed cpp to c++ code block in StdSorting.md

#32: Fix initialize finalize numerics std algorithms

---

source/API/core/view/create_mirror.md
source/API/core/view/deep_copy.md
source/API/core/view/layoutLeft.md
source/API/core/view/layoutRight.md
source/API/core/view/layoutStride.md
source/API/core/view/resize.md
source/API/core/view/subview.md
source/API/core/view/view.md
source/API/core/view/view_alloc.md
source/API/core/view/view_like.md
source/ProgrammingGuide/View.md

- added links, changed cpp to c++ code block in create_mirror.md
- fixed indentation, links, changed cpp to c++ code block in deep_copy.md
- fixed indentation, formatted and fixed grammar layoutLeft.md
- fixed indentation, formatted and fixed grammar layoutRight.md
- fixed indentation, formatted and fixed grammar layoutStride.md
- removed blank lines and fixed indentation in resize.md
- removed blank lines, fixed indentation in subview.md
- added `view_like` to View.rst
- changed cpp to c++ code block in View.md
- added missing view_like to API/core/view
- changed cpp to c++ code block in view_alloc.md
- fixed links in view_like.md
- added links, removed blank line and changed cpp to c++ code block in view.md

#32: Fix API core view

---

source/API/containers/Bitset.md
source/API/containers/DualView.md
source/API/containers/DynRankView.md
source/API/containers/DynamicView.md
source/API/containers/Offset-View.md
source/API/containers/StaticCrsGraph.md
source/API/containers/Unordered-Map.md
source/API/containers/vector.md

- removed blank lines and fixed indentation in Bitset.md
- removed blank lines and fixed indentation in DualView.md
- removed blank lines and fixed indentation in DynamicView.md
- removed blank lines, fixed indentation, grammar and changed cpp to c++ code block in DynRankView.md
- fixed indentation and removed blank lines in Offset-View.md
- added missing StaticCrsGraph to API/containers
- added StaticCrsGraph to containers-index.rst
- change title in StaticCrsGraph.md for consistency
- fixed grammar and removed blank lines in API/containers/Unordered-Map
- formatted title in Unordered-Map.md for consistency
- added missing vector to API/containers
- added `ScatterView` and `vector` to API/containers-index
- formatted title in vector.md for consistency

#32: Fix API containers

---

source/API/core-index.rst
source/API/core/execution_spaces.md
source/API/core/memory_spaces.md
source/API/core/parallel_for.md
source/API/core/parallel_reduce.md
source/API/core/parallel_scan.md

- fixed links and changed cpp to c++ code block in parallel_for.md
- fixed links, changed cpp to c++ code block, fixed headings in parallel_reduce.md
- fixed links, changed cpp to c++ code block, fixed headings in parallel_scan.md
- added `ExecutionSpaceConcept` and other anchors to API/core/execution-spaces
- fixed links, grammar in execution_spaces.md
- added anchors and formatted to API/core/memory_spaces
- fixed links, grammar in memory_spaces.md
- added ParallelForTag, ParallelReduceTag, ParallelScanTag, KokkosConcepts and Traits to core-index.rst

#32: Fix Parallel Execution Spaces

---

source/usecases/Average-To-Nodes.md
source/usecases/Kokkos-Fortran-Interoperability.md
source/usecases/MDRangePolicy.md
source/usecases/MPI-Halo-Exchange.md
source/usecases/OverlappingHostAndDeviceWork.md
source/usecases/SoA-and-AoSoA-with-Cabana.md
source/usecases/TaggedOperators.md
source/usecases/Tasking.md
source/usecases/VirtualFunctions.md

- added links in usecases/Average-To-Nodes.md
- fixed grammar, fixed formatting, removed blank lines added links in usecases/Kokkos-Fortran-Interoperability.md
- fixed grammar, fixed formatting, removed blank lines and added links in usecases/MDRangePolicy.md
- added links to usecases/MPI-Halo-Exchange.md
- fixed grammar, fixed formatting and removed blank lines in usecases/OverlappingHostAndDeviceWork.md
- removed blank lines in usecases/SoA-and-AoSoA-with-Cabana.md
- fixed grammar and fixed links in usecases/TaggedOperators.md
- fixed grammar, fixed links and formatting in usecases/Tasking.md
- removed blank lines, fixed links and fixed grammar in usecases/VirtualFunctions.md

#57: Fixed usecases

---

docs/source/keywords.rst

Add missing CMake Keywords for HIP and fix a couple of typos

Add missing CMake Keywords for HIP

---

wiki-md-files-to-port/API-Reference/Kokkos::View.md

When reading it I think I noticed that the logical expressions in several parts of the documentation should use `then` rather than `than`. Please correct me if my English is wrong here.

Switched 'than' for 'then' in some logical expressions in View documentation

---

README.md

I've found myself having to manually enter the URL or browse back to the Core repo too many times already

Add link to the actual docmentation website in README

---

.gitignore
docs/source/API/core/numerics/mathematical-functions.md

- added /docs/generated_docs to .gitignore
- fixed not rendered `~~` with `<strike></strike>`
BEFORE:
AFTER:
Closes #67

#67: Strikethrough markdown style not recognized

---

docs/source/API/core/Initialize-and-Finalize.rst
docs/source/API/core/ParallelDispatch.rst
docs/source/API/core/View.rst
docs/source/API/core/builtin_reducers.rst
docs/source/API/core/builtinreducers/ReductionScalarTypes.rst

- hid toctree for builtin_reducers.rst and added a table
- fixed formatting and hid toctree in Initialize-and-Finalize.rst
- reduced depth and hid toctree in ParallelDispatch.rst
- Added tables to ParallelDispatch.rst
- hid toctree and add table in ReductionScalarTypes.rst
- hid toctree and add table in View.rst
Below rendered docs, after improvements.

#95: Fixed some rst files rendering

---

docs/source/ProgrammingGuide/Interoperability.md

- fixed links in ProgrammingGuide/Interoperability.md
closes #106

#106: Fix links in ProgrammingGuide/Interoperability

---

docs/source/API/core-index.rst

Fix API Core index C-style memory management link

---

docs/source/ProgrammingGuide/Compiling.md
docs/source/requirements.rst
docs/source/testing-and-issue-tracking/Testing-Process-Details.md

This PR updates the Clang for CUDA , ROCM and Intel compiler versions.

Update supported Clang (CUDA), Intel, and ROCM compiler versions

---

docs/source/API/containers/Bitset.md

This does not work in the code (as expected) and thus should not be listed here.
@dalg24 as discussed briefly on Slack today.

Remove copy from ConstBitset to ConstBitset

---

docs/source/API/core/initialize_finalize/InitializationSettings.md
docs/source/API/core/initialize_finalize/ScopeGuard.md
docs/source/API/core/initialize_finalize/finalize.md
docs/source/API/core/initialize_finalize/initialize.md

Attempted to use reStructuredText instead of Markdown just to give it a try.
I updated every section but `Requirements` and `Semantics`

Update `Kokkos::initialize` API

---

docs/source/API/core/Utilities.rst
docs/source/API/core/execution_spaces.md
docs/source/API/core/memory_spaces.md
docs/source/API/core/utilities/experimental.md

It contains only a minimal hint on the `xnack` rabbithole

Adding Hip spaces ... already without `Experimental`

---

docs/source/API/core/policies/RangePolicy.md

``parallel_for(RangePolicy<>(N), ...)`` doesn't quite work because RangePolicy's constructor requires start,end (not just end).
Replace it with ``parallel_for(RangePolicy<>(0, N), ...)``.

Fix last RangePolicy example

---

docs/source/API/core/execution_spaces.md

I noticed, that the `Default(Host)ExecutionSpace` only exists in examples or in the programming guide. As part of the public interface it should probably have a API documentation. 
I propose a new section because of the alias' dependency on the configuration.

Add DefaultExecutionSpace to API

---

docs/source/ProgrammingGuide/Compatibility.md
docs/source/ProgrammingGuide/Interoperability.md
docs/source/ProgrammingGuide/Kokkos-and-Virtual-Functions.md
docs/source/programmingguide.rst

This supercedes PR #46 & PR #73.
Kokkos Compatibility has been renamed to Backwards & Future Compatibility and put under the Programming Guide as item 12.  The unnecessary comma has been removed.

Add Backwards & Future Compatibility documentation

---

docs/source/API/core/parallel-dispatch/parallel_scan.md

Duplicate of https://github.com/kokkos/kokkos-core-wiki/blob/fdbb4eade33363b65e8086e14f98c020aaac6ae3/docs/source/API/core/parallel-dispatch/parallel_scan.md?plain=1#L31-L37

Remove duplicated parallel_scan with result overload

---

docs/source/videolectures.rst

- created a table with submodules and slides in `videolectures.rst`
Video lectures is now rendered as follows:
closes #79

#79: update lectures links in sidebar

---

docs/source/API/algorithms/std-algorithms/StdMinMaxElement.md
docs/source/API/algorithms/std-algorithms/StdNumeric.md
docs/source/API/algorithms/std-algorithms/StdSorting.md
docs/source/API/core/builtinreducers/BAnd.md
docs/source/API/core/builtinreducers/BOr.md
docs/source/API/core/builtinreducers/LAnd.md
docs/source/API/core/builtinreducers/LOr.md
docs/source/API/core/builtinreducers/Max.md
docs/source/API/core/builtinreducers/MaxLoc.md
docs/source/API/core/builtinreducers/Min.md
docs/source/API/core/builtinreducers/MinLoc.md
docs/source/API/core/builtinreducers/MinMax.md
docs/source/API/core/builtinreducers/MinMaxLoc.md
docs/source/API/core/builtinreducers/MinMaxLocScalar.md
docs/source/API/core/builtinreducers/MinMaxScalar.md
docs/source/API/core/builtinreducers/Prod.md
docs/source/API/core/builtinreducers/ReducerConcept.md
docs/source/API/core/builtinreducers/Sum.md
docs/source/API/core/builtinreducers/ValLocScalar.md
docs/source/API/core/stl-compat/pair.md
docs/source/API/core/utilities/complex.md
docs/source/ProgrammingGuide/Custom-Reductions-Built-In-Reducers-with-Custom-Scalar-Types.md
docs/source/ProgrammingGuide/Custom-Reductions-Custom-Reducers.md
docs/source/ProgrammingGuide/ParallelDispatch.md
docs/source/usecases/MPI-Halo-Exchange.md

From 3.7 onwards, these are no longer necessary, and they are being deleted in the code base.

#151: Clear out references to obviated volatile-qualified overloads

---

docs/source/API/core/c_style_memory_management/malloc.md
docs/source/API/core/c_style_memory_management/realloc.md
docs/source/API/core/view/view.md

This is part of the general discussion of making all user facing memory coarse grained and what happens if the user gets the pointer and changes how the os handles the underlying memory. 
I am not sure about the wording though...maybe it is better to say:
WARNING: calling any function that manipulates the behavior of the memory (e.g. `memAdvise`) on memory managed by `Kokkos` is illegal.

warn in view that pointer manipulation might end in undefined behavior

---

docs/source/API/core/numerics/mathematical-constants.md

Document promotion of math constants to `Kokkos::numbers::`

---

docs/source/API/core/view/Subview_type.md

`Kokkos::Impl::ALL_t` is private so must us `decltype`

Fixup subview doc `decltype(Kokkos::ALL)`

---

docs/source/ProgrammingGuide/ParallelDispatch.md

`foobar` function was missing proper host device annotation.
Drive-change: pass work tags by value

Update programming guide code snippet with worktag code snippet

---

docs/source/ProgrammingGuide/Custom-Reductions-Custom-Reducers.md

Looks like a duplicate function is defined immediately below (maybe used to be `volatile`-qualified before those were removed?)

Remove duplicate function definition

---

docs/source/_ext/cppkokkos.py
docs/source/edit_button_handler.py

- added support for `deprecated-type`
- added support for style change for `deprecated-type`
```rst
``Kokkos::TestView``
====================
.. role:: cppkokkos(code)
:language: cppkokkos
Header File: ``Kokkos_Core.hpp``
Class Interface
---------------
.. cppkokkos:class:: template <class DataType, class... Traits> TestView
A potentially reference counted multi dimensional array with compile time layouts and memory space.
Its semantics are similar to that of :cppkokkos:`std::shared_ptr`.
.. rubric:: Public Member Variables
.. cppkokkos:member:: static constexpr unsigned rank
the rank of the view (i.e. the dimensionality).
.. cppkokkos:type:: const_data_type
The const version of ``DataType``, same as ``data_type`` if that is already const.
.. cppkokkos:type:: uniform_runtime_type …
```

#191: Add deprecated type support and style accordingly

---

docs/source/_ext/cppkokkos.py

- removed word `type` before type definition in `cppkokkos` extension
```rst
``Kokkos::TestView``
====================
.. role:: cppkokkos(code)
:language: cppkokkos
Header File: ``Kokkos_Core.hpp``
Class Interface
---------------
.. cppkokkos:class:: template <class DataType, class... Traits> TestView
A potentially reference counted multi dimensional array with compile time layouts and memory space.
Its semantics are similar to that of :cppkokkos:`std::shared_ptr`.
.. rubric:: Public Member Variables
.. cppkokkos:member:: static constexpr unsigned rank
the rank of the view (i.e. the dimensionality).
.. cppkokkos:type:: const_data_type
The const version of ``DataType``, same as ``data_type`` if that is already const.
.. cppkokkos:type:: uniform_runtime_type
:cppkokkos:`uniform_type` but …
```

#193: Remove type word before type definition in cppkokkos

---

docs/source/known-issues.rst

the file was previously using md format but the extension was rst so causing a warning: 
```
docs/source/index.rst:124: WARNING: toctree contains reference to document 'known-issues' that doesn't have a title: no link will be generated
....
```
this is fixed now.

use proper format in file know-issues to avoid warnings

---

docs/source/API/core/policies/TeamHandleConcept.md

the original concept page was missing nested aliases

add missing aliases to team_handle_concept page

---

docs/source/ProgrammingGuide/Compatibility.md

Added a general warning about adding files starting with `Kokkos_`, and a more specific warning about adding header files starting with `Kokkos_`.

Added verbage about headers starting with `Kokkos_`

---

docs/source/API/core/view/subview.md
docs/source/ProgrammingGuide/Subviews.md

Code snippets do not compile.  Reported on Slack.
Opening just a base for discussion as we could probably update the definition of the subview and make it work instead.

Fixup deducing `Kokkos::Impl::ALL_t` in `Kokkos::Subview` doc

---

docs/source/_ext/cppkokkos.py

The current impl of `kokkosinlinefunction` was only partially working. 
This PR fixes it  so that we can prepend static, etc 
```
.. role:: cppkokkos(code)
:language: cppkokkos
.. cppkokkos:kokkosinlinefunction:: double foo1(int const a);
.. cppkokkos:kokkosinlinefunction:: template<class T> double foo1(int const a);
.. cppkokkos:kokkosinlinefunction:: static double foo2(int const a);
.. cppkokkos:kokkosinlinefunction:: explicit constexpr double foo(int a = 0);
```
Renders as:

fix `kokkosinlinefunction` to support attributes

---

docs/source/keywords.rst

See kokkos/kokkos#5735
Let me know if you'd rather just remove.

Add a deprecated notice for `Kokkos_CXX_STANDARD`

---

docs/source/API/core/utilities/abort.md
docs/source/API/core/utilities/abort.rst

* API/core/utilities/abort transition from .md to .rst
before (.md) | after (.rst)
:----------------: | :-------------:

#120: API-core-utilities-abort from md to rst

---

docs/source/API/containers/Offset-View.rst

* API/containers/Offset-View.rst transition from .md to .rst
before (.md) | after (.rst)
:----------------: | :-------------:

#120: API containers Offset-View transition

---

docs/source/API/simd/where_expression.md

without this, the contents of
the where_expression documentation
spill into the high-level index
for the SIMD API instead of being
their own proper sub-section

fix heading for where_expression

---

docs/source/API/containers/Bitset.rst
docs/source/API/containers/DualView.rst
docs/source/API/containers/DynRankView.rst
docs/source/API/containers/DynamicView.rst
docs/source/API/containers/Offset-View.rst
docs/source/API/containers/StaticCrsGraph.rst
docs/source/API/containers/Unordered-Map.rst
docs/source/API/containers/vector.rst

solves #339 
- adds corresponding header to containers (except scatter view since thre is a pending PR for it) 
- moved to top the alias rst command for domain and removed where not currently needed

add correct header to include for each container

---

docs/source/API/core/utilities/device_id.rst
docs/source/API/core/utilities/num_threads.rst

I am not sure how to annotate in the utilities table of content because it just parses the files header and I don't necessarily want the "since 4.1" in the title but I think a comment in the synopsis is good enough for now.
See kokkos/kokkos#6084

Add a note that device_id and num_threads are only available since 4.1

---

docs/source/API/core/builtinreducers/ReducerConcept.rst

Fixes https://github.com/kokkos/kokkos/pull/6065#issuecomment-1518014632.

Require reducers to define a monoid

---

docs/source/API/core/parallel-dispatch/parallel_reduce.rst

While looking into documentation for https://github.com/kokkos/kokkos/pull/5976, I noticed that the `parallel_reduce` API describes some non-existing overloads and still mentions reductions with a pointer return type.
The documentation for the changes in https://github.com/kokkos/kokkos/pull/5976 seems to be appropriate already. We already say that the return value type must be compatible with the value type of the functor.

Clean-up for parallel_reduce API

---

docs/source/API/core/Macros.rst
docs/source/keywords.rst

I propose to keep things simple and just remove it rather than saying it was removed in 4.1
See kokkos/kokkos#6150

Remove `Kokkos_ENABLE_PROFILING_LOAD_PRINT` and pretend it never existed

---

docs/source/API/core/spaces/partition_space.rst

Corresponds to Kokkos/Kokkos#6167.

Document std::vector overload of partition_space

---

docs/source/_ext/cppkokkos.py

Related to #378
`kokkosinlinefunction` triggered "Duplicate C++ declaration, also defined...". 
This was due to cppkokkos.py missing to include this customization in a couple places. This PR fixes that so that these warnings are solved. 
NOTE: this does not fix the warnings all together, since to get rid of all of them we need #397

Fix cppkokkos to avoid warnings

---

docs/source/API/core/builtinreducers/BAnd.rst

fix `BAnd` according to #397 
| <img width="883" alt="image" src="https://github.com/kokkos/kokkos-core-wiki/assets/18708772/cdf8e35d-5fa9-4c55-97ff-766a69bcc897"> | <img width="890" alt="image" src="https://github.com/kokkos/kokkos-core-wiki/assets/18708772/e6e78eee-0361-4828-9eae-28798b324ea7"> | 
| <img width="718" alt="image" src="https://github.com/kokkos/kokkos-core-wiki/assets/18708772/28d2a811-0c20-4b05-bf59-d137c2222486"> | <img width="721" alt="image" src="https://github.com/kokkos/kokkos-core-wiki/assets/18708772/87804433-77de-4c47-ba5d-2496c939b452">  | 
| <img width="732" alt="image" src="https://github.com/kokkos/kokkos-core-wiki/assets/18708772/e5359d1c-c31f-4563-b9a9-9e522df5f220"> |  <img width="699" alt="image" …

use proper sphinx class syntax for `BAnd`

---

docs/source/API/core/builtinreducers/MinMaxLocScalar.rst

fix `MinMaxLocScalar` according to #397 
| ![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/ad6b9179-5c8d-45a1-a8ef-efa5b476a14a) | <img width="877" alt="image" src="https://github.com/kokkos/kokkos-core-wiki/assets/18708772/a4fd736e-a4a3-4b4b-abeb-4f0514009b0a"> |
| ![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/84841a58-2701-42e6-beb5-f15edb9c7f51) | <img width="882" alt="image" src="https://github.com/kokkos/kokkos-core-wiki/assets/18708772/b8a5f783-3b57-4acf-84ee-406c34ece198"> |

use proper sphinx class syntax for `MinMaxLocScalar`

---

docs/source/API/core/builtinreducers/MinMaxLoc.rst

fix `MinMaxLoc` according to #397 
| ![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/8bd083d2-73de-483e-b9e0-70a7037fe40c) | ![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/9c94e68b-bad5-4a8e-94d9-42beb1174c4b) |
| ![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/28cf8204-b7cd-461d-831d-29e83fb3d9d8) | ![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/0f55ff4f-4d93-4c08-aca7-a6e96a5427ed) |
| ![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/7aa2568c-b10c-4833-853e-1f23f17d5d91) | ![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/118ee53b-58ae-41ff-b71e-c8665776a616) |

use proper sphinx class syntax for `MinMaxLoc`

---

docs/source/API/core/builtinreducers/MinMax.rst

fix `MinMax` according to #397 
| ![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/872491ec-af86-4768-b2ad-34b507a296ec) | ![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/06fa9d63-dc0a-49a3-b85f-dd0a1df5d049) |
|![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/64a347a1-fc73-4a22-ad25-df4c37a44211) | ![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/91f90d8c-1951-4fdb-9a11-1f965054cb17) |
| ![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/c2af4a55-4c9f-42b1-8400-f2fcdb99d677) | ![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/c2d6c7a0-adb0-437f-b917-24d4e07d85f2) |

use proper sphinx class syntax for `MinMax`

---

docs/source/API/core/builtinreducers/MinLoc.rst

fix `MinLoc` according to #397 
| ![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/94e5de9a-e7b4-4cd5-b08f-79bf21add24b) | ![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/53c81c2f-0f54-4a1f-bdf5-38e7eee79d62) |
| ![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/f5966aaa-791d-4ec1-be3a-b1966e0c0916) | ![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/f1459b4d-b5bd-497f-84ab-04da54a5b900) |
| ![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/db839a87-d3d6-448b-82be-4689180dde43) | ![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/3783e0ad-ae39-4eff-b173-98ed82b5b61b) |

use proper sphinx class syntax for `MinLoc`

---

docs/source/API/core/builtinreducers/Min.rst

fix `Min` according to #397 
| ![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/53d531e3-1c79-4891-8886-b587924bcf29) | ![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/bf52cbf9-1de6-4fea-ad07-d397b4d9b34f) |
| ![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/d666808d-6eb3-4ddc-b1fa-ad8bd1d9a1f1) | ![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/cbc6be22-bd79-4201-9052-ef675458fb14) |
| ![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/d8a42bcf-5de6-46dc-86b8-b7801cf4b6af) | ![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/56807b03-b7e1-46c2-b95d-a1d8ec0854f3) |

use proper sphinx class syntax for `Min`

---

docs/source/API/core/builtinreducers/MaxLoc.rst

fix `MaxLoc` according to #397 
| ![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/d6b39542-7b7f-4392-8f80-6edc121ae9b6) | ![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/fd325810-70a3-477f-95d6-84514d1162b6) |
| ![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/272d4683-54bb-4b6a-abad-4958b4a145b6) | ![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/21af26da-da2c-4a90-933d-7df266e8220e) |
| ![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/a5b42da0-21d9-473c-a11b-9e1996de7908) | ![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/d5fac90d-77ef-4278-aae9-7959e6101c01) |

use proper sphinx class syntax for `MaxLoc`

---

docs/source/API/core/builtinreducers/Max.rst

fix `Max` according to #397 
| ![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/1d9a2888-14d0-41d7-91e7-3ca9ed9de422) | ![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/508824cd-51f4-4d57-9430-b1d788bb26d3) |
| ![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/1430240a-fc41-4406-b2e8-0da9133a9f6b) | ![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/d788a007-a693-4d13-9446-8eba3cc2870c) |
| ![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/2328cb77-d51f-43da-afe1-434495e83374) | ![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/05363ecb-b79a-4af0-b1ef-be54ff45ba91) |

use proper sphinx class syntax for `Max`

---

docs/source/API/core/Detection-Idiom.rst

fixes this:
```
Detection-Idiom.rst:2: WARNING: Duplicate explicit target name: "here".
```

fix warning in detection idiom

---

docs/source/API/containers/DynRankView.rst

fixes this:
```
/home/meyer/kokkos-core-wiki/docs/source/API/containers/DynRankView.rst:250: WARNING: Duplicate C++ declaration, also defined at API/containers/DynRankView:220.
Declaration is '.. cppkokkos:function:: DynRankView(const std::string& name, const array_layout& layout)'.
/home/meyer/kokkos-core-wiki/docs/source/API/containers/DynRankView.rst:380: WARNING: Duplicate C++ declaration, also defined at API/containers/DynRankView:75.
Declaration is '.. cppkokkos:function:: constexpr unsigned rank() const'.
```
| :---: | :----: |
| ![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/e634420f-fc7a-42fa-a027-7f3066f00faf) | ![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/0b4ffe60-8360-4c9e-9d58-44480ff60807) | 
| …

#420: Fix warning in DynRankView.rst

---

docs/source/API/core/view/view.rst

fixes this:
```
/kokkos-core-wiki/docs/source/API/core/view/view.rst:28: WARNING: cppkokkos:func targets a class (LayoutRight).
/kokkos-core-wiki/docs/source/API/core/view/view.rst:32: WARNING: cppkokkos:func targets a class (LayoutLeft).
/kokkos-core-wiki/docs/source/API/core/view/view.rst:36: WARNING: cppkokkos:func targets a kokkosinlinefunction (LayoutStride).
```
| :---: | :----: |
| ![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/b9f823ac-45eb-4d81-bbca-7f1aacc0d535) | ![image](https://github.com/kokkos/kokkos-core-wiki/assets/62652182/4e414202-cb7c-470b-b389-3c40ff7ff2ba) |

#420: Fix warning in view.rst

---

docs/source/API/core/parallel-dispatch/parallel_for.rst

On behalf of @dalg24 
citation: "Passing the `int` by reference is not smart here"

Removed reference for simple `parallel_for`

---

docs/Makefile

Ensure that the CI fails if the PR code generates warnings.
Use Sphinx's native options:
- ``-W``
**Turn warnings into errors.** This means that the build stops at the first warning and sphinx-build exits with exit status 1.
- ``--keep-going``
With -W option, **keep going processing when getting warnings to the end of build**, and sphinx-build exits with **exit status 1**.
Link to Sphinx documentation: https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-W
This option finishes the build. This displays all warnings, if any, and makes it easier for the developer to resolve them. If you remove this option, the build stops at the first warning encountered and displays only the first warning. It might be better to remove this option, whatever you prefer.
This …

#378: Add sphinx-build options to ensure that the documentation builds warning free

---

docs/source/keywords.rst

The correct spelling is `Kokkos_ARCH_ARMV8_THUNDERX2`.

Remove non-existant Kokkos_ARCH_ARMV8_TX2 option

---

docs/source/keywords.rst

This PR is related to https://github.com/kokkos/kokkos/pull/6266. It adds the documentation for the new naming convention and a table that help users to find the correct flag.

Add documentation for new AMD GPU naming convention

---

docs/source/requirements.rst

This should really point to the main repository and is currently not displayed as a link at all.

Fix a link in requirements.rst

---

docs/source/API/core/numerics/mathematical-constants.rst
docs/source/known-issues.rst

See https://github.com/kokkos/kokkos/pull/5897#issuecomment-1750690290

Add taking the address of math constants to known issues

---

docs/source/API/core/initialize_finalize/InitArguments.rst
docs/source/API/core/numerics/mathematical-constants.rst
docs/source/API/core/numerics/mathematical-functions.rst

Document removals in version 4.3

---

docs/source/API/core/utilities/printf.rst

We had a report on Slack about getting an `namespace "Kokkos" has no member "printf"` error.
Nothing in the documentation captures that it was added in 4.2

Add a note that `Kokkos::printf` is only available in release 4.2

---

docs/source/API/core/c_style_memory_management/malloc.rst

The documentation refers to Kokkos::realloc instead of Kokkos::kokkos_realloc

Fixup Kokkos::[kokkos_]realloc

---

docs/source/ProgrammingGuide/Compiling.md

This script is not officially supported by us for external users.

Remove generate_makefile.bash mentioning

---

docs/source/API/core/utilities/abort.rst

Added in kokkos/kokkos#6445 and mentioned in the 4.2 changelog

Document the new header `<Kokkos_Abort.hpp>`

---

docs/source/API/core/Utilities.rst
docs/source/API/core/utilities/assert.rst

Doc was missing which is awkward considering the 4.2 release changelog features the new `<Kokkos_Assert.hpp>` headers.
I deliberately omitted `KOKKOS_ENSURES` and `KOKKOS_EXPECTS`.
I also chose to ignore that the `KOKKOS_ENFORCE_CONTRACTS` macro is also used to decide whether to check the condition is true or not.  We might want to get rid of it but that is not the place to have this debate.

Document `KOKKOS_ASSERT` macro

---

docs/source/faq.rst
docs/source/index.rst

add an initial FAQ

---

docs/source/usecases/SoA-and-AoSoA-with-Cabana.md

This page had never been updated since the device type template parameter was deprecated on the Cabana side.
@streeve please review

Update `AoSoA` API in Cabana's use case

---

docs/source/API/core/policies/MDRangePolicy.rst
docs/source/API/core/policies/RangePolicy.rst

Related: https://github.com/kokkos/kokkos/pull/6617
Added a note under the constructor sections of `RangePolicy` and `MDRangePolicy` about the precondition that is newly added by https://github.com/kokkos/kokkos/pull/6617.

Update RangePolicy and MDRangePolicy on the bounds precondition

---

docs/source/API/core-index.rst
docs/source/API/core/Profiling.rst
docs/source/API/core/profiling/profiling_section.rst
docs/source/API/core/profiling/scoped_region.rst

I keep getting the following error
```
docs/source/API/core/profiling/scoped_region.rst:40: WARNING: Could not lex literal_block as "cpp". Highlighting skipped.
```
I would appreciate some help to fix
I intend to get into the documentation of the profiling interface in follow up PRs.
This PR specifically documents the `Profiling::ProfilingSection` and `Profiling::ScopedRegion` RAII-style helper classes.

Add Profiling API section and document `ProfilingSection` and `ScopedRegion`

---

docs/source/API/core/Utilities.rst
docs/source/API/core/utilities/swap.rst

~~Pending on kokkos/kokkos#6678~~
Documenting kokkos/kokkos#6697

Document `Kokkos::kokkos_swap` and associated new public header

---

docs/source/API/core/Utilities.rst
docs/source/API/core/utilities/device_id.rst
docs/source/API/core/utilities/num_devices.rst
docs/source/API/core/utilities/num_threads.rst

Document `Kokkos::num_devices()`

---

docs/source/ProgrammingGuide/HierarchicalParallelism.md

Delete outdated note about `TeamPolicy::set_scratch_size()`

---

docs/source/API/core/KokkosConcepts.rst
docs/source/API/core/Macros.rst
docs/source/ProgrammingGuide/Compiling.md
docs/source/ProgrammingGuide/View.md
docs/source/keywords.rst

Following the merge of kokkos/kokkos#6791

Remove all mentions of `Kokkos::Experimental::HBWSpace` and memkind

---

docs/source/API/core/Macros.rst
docs/source/ProgrammingGuide/Compiling.md
docs/source/keywords.rst

Remove mentions of librt as a third-party library

---

docs/source/keywords.rst

Put some order in our backends, options, and architectures
Fix #370
Grouping backends by serial, host parallel, and device
Grouping architectures by CPU vs GPU and subdivide based on vendors
I focused on the NVIDIA GPUs.  AMD and Intel GPUs can be tackled in follow ups.
CPUs could use some TLC too.
This can obviously be improved further but I think it is already worth merging.

Improve documentation of the CMake options available

---

docs/source/API/core/Macros.rst
docs/source/keywords.rst

Mention oneDPL TPL

---

docs/source/keywords.rst

Avoid redundant information in the description of Intel GPUs and add some examples of particular guards.

Improve description for Intel GPU architectures

---

docs/source/keywords.rst

Documentation for https://github.com/kokkos/kokkos/pull/6793

Add documentation about the new CMake keyword: rocthrust

---

docs/source/API/core/execution_spaces.rst

List ``operator==`` as non-member functionality of execution spaces. I had a case where I wanted to use this, but it wasn't listed here and I misread it as a private declaration in the actual code

Document operator== for execution spaces

---

docs/source/API/algorithms/std-algorithms/all/StdForEach.md

To reflect the changes from kokkos/kokkos#6910
We were returning a copy of the function object argument and now return nothing to align with `std::for_each` overload that takes an execution policy.  This is an experimental facility and advertising that we return `void` is compatible with our policies so we don't need to mention the change in the doc.

Change `Experimental::for_each` return type to void

---

docs/source/known-issues.rst

Related to https://github.com/kokkos/kokkos/pull/6801#issuecomment-1969888881.

Document issue with Kokkos::sort and comparators

---

docs/source/API/simd/simd.md
docs/source/API/simd/where_expression.md

Updated missing documentations on `simd` and `where_expression`.
This also addresses #517.

Update simd and simd where_expression docs

---

docs/source/keywords.rst

Fix #518
Rework categories
* General options
* Debugging
* Backend-specific options
* Development
to help users navigate options.  In particular, add a note to hints that dev options are not intended for them to use.
Document `Kokkos_ENABLE_DEPRECATION_WARNINGS` that was missing and `Kokkos_ENABLE_ATOMICS_BYPASS` that was added in 4.3
Indicate that `Kokkos_ENABLE_DEPRECATED_CODE_3` is removed in 4.3

Reorganize options and document BYPASS_ATOMICS and DEPRECATION_WARNINGS

---

docs/source/API/core/parallel-dispatch/parallel_scan.rst

Related to https://github.com/kokkos/kokkos/issues/6897.
This documents current behavior. The `Serial` backend calls the functor only once with `final=true` while the `Cuda` backend calls the functor once with `final=false` in its first kernel,  once with `final=false` and once with `final=true` in its second kernel.
This led to hard-to-understand problems when trying to cache results for `final=false`. The very least we can do is to document current restrictions better.

Clarify parallel_scan behavior

---

docs/source/API/core/builtinreducers/ReducerConcept.rst

We didn't mention the `final` member function in the reducer concept and providing an `init` member function is optional as well.

Reducer concept: Document final and mark init as optional

---

docs/source/API/core/policies/RangePolicy.rst

This updates the existing RangePolicy constructor documentation as per https://github.com/kokkos/kokkos/pull/6845 and adds a section for the CTAD constructors as per https://github.com/kokkos/kokkos/pull/6850.
This addresses issue #519 and part of issue #515.

RangePolicy constructor updates from Release 4.3

---

docs/source/ProgrammingGuide/View.md

oh, and "polymorpic" -> "polymorphic".
The "CAS" -> "compare-and-swap (CAS)" change is different in quality than the rest, as it wasn't a typo. But for a Wiki, I think it's nicer this way.

Added some apostrophes, a comma, and spelled out CAS

---

docs/source/ProgrammingGuide/Initialization.rst

A copy paste of the help displayed by `--kokkos-help`

Add missing command line option `--kokkos-device-id`

---

docs/source/ProgrammingGuide/View.md

We don't necessarily call a `parallel_for` functor for initializing a `View` but might just call `memset`. Thus, this pull request avoids spelling out implementation details about the initialization mechanism.

Don't promise that the View constructor will call a parallel_for for initialization

---

docs/source/known-issues.rst

Older Nvidia GPU can be tricky to use with Kokkos, write

Suggest to disable cudamallocasync for legacy device

---

docs/source/API/core/view/create_mirror.rst

Added a paragraph to "Usage", before the code example, and added comments to the code example.
I was thinking about changing the variable names in the second half of the code example from `host_mirror_space*` to `space_mirror*`, as now they don't *have* to be in host space, if another space is provided. Though I'm not yet familiar enough with Kokkos to know whether `ExecName()` is pseudo code or evaluates to the default execution space or something like that.

create_mirror and create_mirror_view: clarified difference

---

docs/source/API/core/view/view.rst

spotted it when looking at:
https://github.com/kokkos/kokkos/blob/e0d99fdd79909779f17009fc030d7221520f7feb/core/src/Kokkos_View.hpp#L1379

std::string as returntype of view.label()

---

docs/source/API/core/execution_spaces.rst

the page https://kokkos.org/kokkos-core-wiki/API/core/execution_spaces.html
doesn't mention `Kokkos::Threads`
yet `Threads` is referenced from https://kokkos.org/kokkos-core-wiki/API/core/Execution-Policies.html

Mention Kokkos::Threads

---

docs/source/API/core/execution_spaces.rst

Link to memory_spaces.html#memoryspaceconcept led to the top of that page, rather than to memory_spaces.html#kokkos-memoryspaceconcept

execution_spaces.rst: fixed link to memoryspaceconcept

---

docs/source/API/core/memory_spaces.rst

Seems that all links of the type
"the documentation on the MemorySpace() concept."
pointed to 
https://kokkos.org/kokkos-core-wiki/API/core/memory_spaces.html#memoryspaceconcept
which doesn't exist. But
...html#kokkos-memoryspaceconcept
does, so now they hopefully point that way. Same goes for executionspaceconcept.

memory_spaces.rst: corrected links to (memory|execution)spaceconcept header

---

docs/source/API/core/Execution-Policies.rst
docs/source/API/core/execution_spaces.rst

In a discussion on slack it came up, that the `IndexType` of `ExecutionPolicy` does not always default to `int64_t` as stated in the documentation.
From looking at the implementation it defaults to the `size_type` of the `MemorySpace` that is associated with the `ExecutionSpace` given to the `ExecutionPolicy`. Therefore, this PR adds a table with the backend-specific `size_type` to the `MemorySpace` page and adds a link to it in the common arguments page of the `ExecutionPolicy` page.

List backend-specific `IndexType` for `ExecutionPolicy`

---

docs/source/API/core/policies/MDRangePolicy.rst
docs/source/API/core/policies/NestedPolicies.rst
docs/source/API/core/policies/RangePolicy.rst

It just makes more sense to not repeat ourselves I think...
Came up in the wake of #552

favor link to common template arguments page over copy of the table in many `ExecutionPolicies`

---

docs/source/testing-and-issue-tracking/Testing-Processes.md

Partial fix for kokkos/kokkos#7177

Say where one can find out what clang-version we use

---

docs/source/API/core/policies/RangePolicy.rst

I chose to use a "note", but I'm happy to switch to a "warning" or bold text (done other places) or other suggestions.

Add note about ChunkSize explicit constructor since 4.4

---

docs/source/API/core/policies/MDRangePolicy.rst

Related to https://github.com/kokkos/kokkos/pull/6839.
Added descriptions for `tile_size_recommended()` and `max_total_tile_size()` in `MDRangePolicy`.

Add descriptions for tile size getters in MDRangePolicy

---

docs/source/ProgrammingGuide/View.md

`Kokkos::ViewAllocateWithoutInitializing` is not supposed to be used, or at least we shouldn't show it exists.

core(view): do not show `ViewAllocateWithoutInitializing` in the doc

---

docs/source/ProgrammingGuide/View.rst

As mentioned in #569, I'll need the `View.md` to understand `RST`. So I need to renamed it. And so `Sphinx` complains.
Changes:
1. Sections, subsections and so on.
2. Code blocks.
3. References (to sections, footnote).
4. Italic.
5. The table becomes a `csv-table`.

core(view): changes due to conversion from md to rst

---

docs/source/ProgrammingGuide/View.rst

- `reference_is_lvalue` should be `reference_type_is_lvalue`
- use `octicon` for the accessibilty table to improve appearance
- remove HIP from the table since Cuda is used as an example and it doesn't make sense to ask for accessibility between a Cuda execution space and HIP memory spaces since they can't be available at the same time anyway.

Improve ProgramminGuide/View

---

docs/source/API/core/builtinreducers/MinLoc.rst

This PR adds example code from Compiler Explorer to `MinLoc` built-in reducer.

Add example code referenced in issue #452 

---

docs/source/API/containers/Unordered-Map.rst

Documentation was missing for the following public functions
- `create_copy_view(UnorderedMap src)`
- `allocate_view(UnorderedMap src)`
- `deep_copy_view(UnorderedMap src)`
and non-member functions
- `deep_copy(UnorderedMap dst, UnorderedMap src)`
- `UnorderedMap::HostMirror create_mirror(UnorderedMap src)`

Add missing documentation for UnorderedMap

---

docs/source/ProgrammingGuide/View.rst

This PR describes what `Kokkos::WithoutInitialization` implies.

core(view): warn about the implications of without initializing

---

docs/source/API/core/view/layoutLeft.rst
docs/source/API/core/view/layoutRight.rst
docs/source/API/core/view/layoutStride.rst
docs/source/API/core/view/view_alloc.rst

Following discussion https://github.com/kokkos/kokkos/pull/7320#issuecomment-2353200996, as of Kokkos 4.4, `Kokkos_View.hpp` and `Kokkos_Layout.hpp` are not public headers.

Update public headers

---

docs/source/keywords.rst

Following a discussion with @masterleinad over Slack.
The `BUILD.md` in the Kokkos source repo used to list (all?) `Kokkos_` prefixed CMake options, until April 2023 when it started to refer readers to the Wiki page: https://github.com/kokkos/kokkos/commit/83873a62bb4d6ce47ec39e7775300b7ecdddfe73#diff-40f60e1037245d7b8a98a7325d53890a717da9979adeb54a61a795c4ba07f9c9R114
Both `Kokkos_ENABLE_IMPL_HPX_ASYNC_DISPATCH` and `Kokkos_ENABLE_IMPL_CUDA_MALLOC_ASYNC` weren't carried over to the Wiki at the time. The latter is especially confusing, given its changing default settings and issues with Cray MPICH on NERSC Perlmutter, ALCF Polaris, and LANL Venado, etc. https://github.com/kokkos/kokkos/pull/7353
I have re-added them, plus added two other helpful CMake comments that @masterleinad had …

Re-add 2x missing CMake IMPL_ flags to the Wiki

---

docs/source/keywords.rst

CUDA_LDG_INTRINSIC has no effect since 2019 and the option is deprecated since 4.0
I think it is better to just remove it form the list

Mark CUDA_LAMBDA as deprecated and get rid of CUDA_LDG_INTRINSIC

---

docs/source/API/core/policies/TeamPolicy.rst

Related to https://github.com/kokkos/kokkos/pull/7423.

team_size_max/recommended: Clarify that team_size should be checked

---

docs/source/API/core/execution_spaces.rst
docs/source/API/core/memory_spaces.rst
docs/source/ProgrammingGuide/Initialization.rst

Related to https://github.com/kokkos/kokkos/pull/7171.

Promote SYCL from Experimental

---

docs/source/API/core/Task-Parallelism.rst
docs/source/usecases/Tasking.md

Related to https://github.com/kokkos/kokkos/pull/7393.

Deprecate Tasking interface

---

docs/source/API/core/KokkosConcepts.rst
docs/source/API/core/execution_spaces.rst

Related to https://github.com/kokkos/kokkos/issues/7319.
- in_parallel is deprecated
- execution spaces are regular now
- wake and sleep don't exist anymore
- we missed concurrency

Update concept for execution space instances

---

docs/source/known-issues.rst

Writing an initial stub for this know issues but it might be a good idea to add more to this documenting paragraph

known-issues: cuda 11.x with modern glibc and CMake

---

docs/source/requirements.rst

Update Compiler Version Requirement document (`requirements.rst`) for the OpenACC backend.

Update Compiler Version Requirements for the OpenACC backend

---

docs/source/faq.rst
docs/source/quick_start.rst

Users should be able to get their first program up and running after reading this section.

Improve the Get Started section

---

.github/workflows/deploy_docs.yml

This is an attempt to fix the permissions error on the last merge. The code is inspired from https://github.com/actions/upload-pages-artifact

Update action to deploy to GitHub pages

---

docs/source/API/core/parallel-dispatch/parallel_for.rst
docs/source/API/core/parallel-dispatch/parallel_reduce.rst
docs/source/API/core/parallel-dispatch/parallel_scan.rst

This question came up in the slack whether the operator might be called multiple times.

Clarify parallel semantics of calling functor operator

---

docs/source/API/containers/DualView.rst

Related to https://github.com/kokkos/kokkos/pull/7712.
This addresses usage for unfied memory architectures or `Kokkos::SharedSpace`/`Kokkos::SharedHostPinnedSpace` in particular.

Improve DualView documentation

---

docs/source/API/core/parallel-dispatch/parallel_scan.rst
docs/source/API/core/policies/TeamThreadRange.rst

Related to https://github.com/kokkos/kokkos/issues/5635

#5635: Update documentation to cover new overloads for parallel_scan

---

docs/source/API/simd/simd.md
docs/source/API/simd/simd_mask.md
docs/source/API/simd/where_expression.md

Updated descriptions on simd type aliases (`native_simd` and `native_simd_mask` ) based on changes in https://github.com/kokkos/kokkos/pull/7472.

Fix descriptions on simd native_simd type alias

---

docs/source/ProgrammingGuide/HierarchicalParallelism.md

This commit modifies the snippet illustrating how to use a method of the ``member_type`` type to trigger a reduction. There were 3 adjustments:
1. The name of the triggered method was invalid: the `TeamHandleConcept` concept doesn't specify a ``reduce`` method. I adjusted the name to instead reference the [`team_reduce` method](https://kokkos.org/kokkos-core-wiki/API/core/policies/TeamHandleConcept.html#_CPPv4I0ENK17TeamHandleConcept11team_reduceEvRK11ReducerType). (maybe the way it was written was correct at some point in an earlier version?)
2. Consequently, I also needed to adjust how the reduction was called
3. I fixed some inconsistent indentation within the snippet
There were 2 areas where I was a little uncertain on what to do:
- I couldn't tell if whether it was idiomatic to …

Fix inconsistency in ``team_member.reduce`` sample code snippet

---

docs/source/API/containers/ScatterView.rst

Trying to instantiate a ScatterView while specifying its template parameters didn't work as written in the doc.
You can check it here: https://godbolt.org/z/Me1jKezjq
Also added a small description on how to use ScatterView and a description for each template parameter (copied from the cheatsheet).
All of this descriptions may be wrong and need to be checked by someone more familiar with ScatterViews.

Correct ScatterViews template parameters order

---

docs/source/API/simd/simd.md
docs/source/API/simd/simd_mask.md
docs/source/API/simd/where_expression.md
docs/source/ProgrammingGuide/SIMD.md

Updated simd documentations
- Added notes indicating removal of `reference` and subscript operators returning references
- Added compound assignment operators and reduction functions
- Modified examples to use correct simd types and simd flags
- Removed all occurrences of `native_simd` and `native_simd_mask`

update simd documentation for kokkos 4.6

---

docs/source/API/core-index.rst
docs/source/API/core/MultiGPUSupport.rst

Multi GPU was not yet documented, seems like we needed something for this.
There is much more that could be added
- timings
- show how to alloc unmanaged views
- show how to use the execution space for view alloc, policy creation, fencing
- link the tutorial?
Let me know your thoughts.

Add initial MultiGPU documentation

---

docs/source/API/core/execution_spaces.rst
docs/source/get-started/configuration-guide.rst

Document SYCL backend behavior with no selected GPU architecture

---

docs/source/conf.py

This PR ensures that the year in the copyright footnote is the year the documentation was generated for the last time.

conf: make the year always up-to-date

---

docs/source/get-started/configuration-guide.rst

Document the option  `KOKKOS_ARCH_RISCV_U74MC` to build Kokkos on Sifive Unmatched boards

Add Sifive Unmatched option

---

.github/workflows/deploy_docs.yml
docs/source/ProgrammingGuide/Graph.rst
docs/source/conf.py
docs/source/programmingguide.rst

We are starting to document `Kokkos::Experimental::Graph`.
This PR sets the basement for it.
Joint work with @maartenarnst.
~~Drive-by change: ensure that the year corresponds to the moment the documentation was generated.~~ (see #649)
Some additional work was need to get `graphviz` working:
1. `apt` install the `graphviz` package
2. but the CI was running on a runner, not in a container, so I got permission denied
3. so I added `container:`
4. and `pip` was not found
5. so I ended up using the `python:3.10` image.
- extracted from #565.

core(graph): initial doc

---

docs/source/get-started/configuration-guide.rst

This PR fixes two broken links in the CMake keywords page

Fix two broken links in the cmake keywords page

---

docs/source/API/core/view/view.rst
docs/source/ProgrammingGuide/Interoperability.md

The issue is in the interoperability page an unmanaged view is given the syntax `View<..., Unmanaged>` where the correct syntax is `View<..., MemoryTraits<Unmanaged>>`.
I have also added an example so that the memory traits is easier to use, depicting the usage as bit flags rather than template tags to ease any confusion.
This threw me a little bit, it is in other places in the documentation so not a major issue but would be nice if it were correct here

Fixes memory traits example.

---

docs/source/ProgrammingGuide/Compiling.md
docs/source/get-started/building-from-source.rst

There was confusion by me and someone else who raised an issue trying to use `nvcc_wrapper` on windows. 
I think the wording of the `nvcc_wrapper` section in `Compiling.md` give the wrong impression. I have changed said wording (though I think it could be better) and added a note in `building_from_source.rst` so that what to do on windows can be seen easier.
I would also suggest adding something to the tutorials for windows/MSVC compilation. My current solution is not portable.
Thanks

Aid in msvc building

---

docs/source/ProgrammingGuide/Compiling.md

Add a note that GNU Makefiles are deprecated and will be removed with Kokkos 5.0.

Make file deprecation

---

docs/source/API/containers/DualView.rst

@JBludau found the current documentation for `DualView::resize` not clear enough in https://github.com/kokkos/kokkos/pull/8011#discussion_r2056021224. Thus, this pull request adds another advice for calling `sync` after `resize`.

DualView: Be more explicit about synchronization behavior for resize

---

.github/workflows/deploy_docs.yml
build_requirements.txt

This cleans up a few things, and we can do this now that we are not maintaining our own domain :)
* The newer sphinx version fixes a cross referencing bug that I ran into while refactoring the View documentation
* The newer Foro version makes `versionadded` and `versionchanged` directives look nicer
* The newer Foro version makes expressions render not weirdly (i.e. `:cpp:expr:`)

update sphinx and foro versions

---

docs/source/ProgrammingGuide/Initialization.rst

These links don't work since they are pointing to https://kokkos.org/kokkos-core-wiki/ProgrammingGuide/Table_cli-opts which doesn't exist. This version will use https://kokkos.org/kokkos-core-wiki/ProgrammingGuide/Initialization.html#table-cli-opts instead.
Also fix the `--kokkos-device-id=INT` entry.

Fix links to Command-line options for Kokkos::initialize and fix an entry

---

docs/source/API/core/execution_spaces.rst
docs/source/API/core/memory_spaces.rst
docs/source/API/core/view/create_mirror.rst
docs/source/API/core/view/view.rst
docs/source/templates/class_api.rst

This fixes a few issues and makes View a cross-referenceable entity. Also it brings everything in line stylistically with how we want to write documentation (i.e. use of cross-references and sphinx entities)

refactor view documentation

---

docs/source/API/containers/DynRankView.rst
docs/source/API/core/view/view.rst

In the documentation, `required_allocation_size` takes 9 arguments, even though Views are up to 8D (and DynRankView is up to 7D). The function actually takes 8 arguments (the last arg shouldn't be used for the DynRankView version)

fix the number of arguments of `required_allocation_size`

---

docs/source/API/core/Execution-Policies.rst

Description of the WorkTag contained a typo that made parsing a sentence ambiguous.

Correct a typo in the description of the worktag of an ExecutionPolicy

---

docs/source/get-started/configuration-guide.rst
docs/source/known-issues.rst

~Some documentation for Kokkos requiring to be built with the CMake language feature. Since `kokkos_compilation` since `kokkos_compilation` is broken see [here](https://github.com/kokkos/kokkos/issues/7144) for a momentary fix.~
~[7582](https://github.com/kokkos/kokkos/pull/7582) is a related refactor of the build system but is independent of this PR~
Stripped everything except adding the build option and a hint for msvc. fixes https://github.com/kokkos/kokkos-core-wiki/issues/661

Document `Kokkos_ENABLE_COMPILE_AS_CMAKE_LANGUAGE`

---

docs/source/ProgrammingGuide/Custom-Reductions-Custom-Reducers.md

This fixes a minor typo kind of error, where two `operator+=` overloads have been defined in the example code for the custom reducer.
The overload returning a reference to the object has been retained. Even though chaining `operator+=` is a less likely scenario, [other use cases](https://stackoverflow.com/questions/36232136/return-type-of-operator-while-overloading) like implementing `operator+` using `operator+=` and writing to an output stream are worth addressing.

Remove unnecessary overload in custom reducer

---

docs/source/API/core/view/memoryTraits.rst
docs/source/ProgrammingGuide/View.rst

Fixes issue [682](https://github.com/kokkos/kokkos-core-wiki/issues/682).
The goal is to document the deprecated managed memory trait.

About deprecated managed memory trait

---

docs/source/API/core/spaces/partition_space.rst

https://github.com/kokkos/kokkos/pull/8114 changed return type of one `partion_space()` function to enable structured bindings. 
Also, now uses structured binding in doc example, and fixes a typo where the code text was messed up.

Update partition space docs.

---

docs/source/API/core/atomics/atomic_op_fetch.rst

Compared to `atomic_fetch_op` where we use `old_value`.

old_value -> new_value in atomic_op_fetch
